• Builder raising > error C3861: 'META_CONPRINTF': identifier not found on META_CONPRINTF usage, so it's disabled for now • added sqlite3.c in AMBuilder